[check]
preview = true
select = ["C", "E", "S", "MOD"]
ignore = [
  "superfluous-implicit-none",
  "implicit-external-procedures",
  "interface-implicit-typing",
]
file-extensions = ["f90", "F90"]
line-length = 78
fix = true
# output-format =  "full"
# show-fixes = false
# unsafe-fixes = true
