#!/bin/bash

# cd ${lib}
# ar rcs ${lib}/libeasifem.a ${lib}/*.o
# cd -

echo "entering easifem library..."
cd $EASIFEM_LIB
echo "---- making shared library"
ar rcs ${EASIFEM_LIB}/libeasifem.a ${EASIFEM_LIB}/*.o
echo "exiting easifem library.."
cd -