! raylib.f90
!
! A collection of auto-generated Fortran 2018 interface bindings to
! raylib 5.1.
!
! Author:  Philipp Engel
! Licence: ISC
!
!> author: Vikas Sharma, Ph. D.
! date: 2024-05-02
! summary: I have subdivided the big raylib module into smaller modules

MODULE RaylibEnums
USE, INTRINSIC :: ISO_C_BINDING
IMPLICIT NONE(TYPE, EXTERNAL)
PRIVATE

! ConfigFlags
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_VSYNC_HINT = INT(z'00000040')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_FULLSCREEN_MODE &
                                          = INT(z'00000002')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_RESIZABLE &
                                          = INT(z'00000004')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_UNDECORATED &
                                          = INT(z'00000008')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_HIDDEN &
                                          = INT(z'00000080')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_MINIMIZED &
                                          = INT(z'00000200')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_MAXIMIZED &
                                          = INT(z'00000400')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_UNFOCUSED &
                                          = INT(z'00000800')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_TOPMOST &
                                          = INT(z'00001000')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_ALWAYS_RUN &
                                          = INT(z'00000100')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_TRANSPARENT &
                                          = INT(z'00000010')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_HIGHDPI &
                                          = INT(z'00002000')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_WINDOW_MOUSE_PASSTHROUGH &
                                          = INT(z'00004000')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_BORDERLESS_WINDOWED_MODE &
                                          = INT(z'00008000')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_MSAA_4X_HINT &
                                          = INT(z'00000020')
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FLAG_INTERLACED_HINT &
                                          = INT(z'00010000')

! TraceLogLevel
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_ALL = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_TRACE = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_DEBUG = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_INFO = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_WARNING = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_ERROR = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_FATAL = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: LOG_NONE = 7

! KeyboardKey
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_NULL = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_APOSTROPHE = 39
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_COMMA = 44
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_MINUS = 45
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_PERIOD = 46
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SLASH = 47
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_ZERO = 48
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_ONE = 49
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_TWO = 50
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_THREE = 51
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_FOUR = 52
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_FIVE = 53
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SIX = 54
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SEVEN = 55
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_EIGHT = 56
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_NINE = 57
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SEMICOLON = 59
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_EQUAL = 61
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_A = 65
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_B = 66
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_C = 67
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_D = 68
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_E = 69
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F = 70
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_G = 71
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_H = 72
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_I = 73
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_J = 74
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_K = 75
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_L = 76
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_M = 77
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_N = 78
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_O = 79
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_P = 80
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_Q = 81
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_R = 82
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_S = 83
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_T = 84
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_U = 85
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_V = 86
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_W = 87
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_X = 88
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_Y = 89
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_Z = 90
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT_BRACKET = 91
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_BACKSLASH = 92
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT_BRACKET = 93
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_GRAVE = 96
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SPACE = 32
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_ESCAPE = 256
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_ENTER = 257
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_TAB = 258
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_BACKSPACE = 259
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_INSERT = 260
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_DELETE = 261
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT = 262
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT = 263
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_DOWN = 264
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_UP = 265
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_PAGE_UP = 266
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_PAGE_DOWN = 267
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_HOME = 268
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_END = 269
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_CAPS_LOCK = 280
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_SCROLL_LOCK = 281
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_NUM_LOCK = 282
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_PRINT_SCREEN = 283
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_PAUSE = 284
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F1 = 290
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F2 = 291
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F3 = 292
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F4 = 293
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F5 = 294
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F6 = 295
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F7 = 296
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F8 = 297
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F9 = 298
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F10 = 299
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F11 = 300
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_F12 = 301
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT_SHIFT = 340
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT_CONTROL = 341
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT_ALT = 342
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_LEFT_SUPER = 343
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT_SHIFT = 344
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT_CONTROL = 345
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT_ALT = 346
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_RIGHT_SUPER = 347
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KB_MENU = 348
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_0 = 320
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_1 = 321
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_2 = 322
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_3 = 323
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_4 = 324
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_5 = 325
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_6 = 326
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_7 = 327
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_8 = 328
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_9 = 329
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_DECIMAL = 330
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_DIVIDE = 331
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_MULTIPLY = 332
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_SUBTRACT = 333
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_ADD = 334
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_ENTER = 335
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_KP_EQUAL = 336
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_BACK = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_MENU = 82
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_VOLUME_UP = 24
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: KEY_VOLUME_DOWN = 25

! MouseButton
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_LEFT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_RIGHT = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_MIDDLE = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_SIDE = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_EXTRA = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_FORWARD = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_BUTTON_BACK = 6

! MouseCursor
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_DEFAULT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_ARROW = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_IBEAM = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_CROSSHAIR = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_POINTING_HAND = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_RESIZE_EW = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_RESIZE_NS = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_RESIZE_NWSE = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_RESIZE_NESW = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_RESIZE_ALL = 9
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MOUSE_CURSOR_NOT_ALLOWED = 10

! GamepadButton
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_UNKNOWN = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_FACE_UP = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_FACE_RIGHT = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_FACE_DOWN = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_FACE_LEFT = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_FACE_UP = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_FACE_DOWN = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_FACE_LEFT = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_TRIGGER_1 = 9
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_TRIGGER_2 = 10
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_TRIGGER_1 = 11
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_TRIGGER_2 = 12
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_MIDDLE_LEFT = 13
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_MIDDLE = 14
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_MIDDLE_RIGHT = 15
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_LEFT_THUMB = 16
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_BUTTON_RIGHT_THUMB = 17

! GamepadAxis
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_LEFT_X = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_LEFT_Y = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_RIGHT_X = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_RIGHT_Y = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_LEFT_TRIGGER = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GAMEPAD_AXIS_RIGHT_TRIGGER = 5

! MaterialMapIndex
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_ALBEDO = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_METALNESS = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_NORMAL = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_ROUGHNESS = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_OCCLUSION = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_EMISSION = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_HEIGHT = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_CUBEMAP = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_IRRADIANCE = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_PREFILTER = 9
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_BRDF = 10

INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_DIFFUSE = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: MATERIAL_MAP_SPECULAR = 1

! ShaderLocationIndex
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_POSITION = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_TEXCOORD01 = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_TEXCOORD02 = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_NORMAL = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_TANGENT = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VERTEX_COLOR = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MATRIX_MVP = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MATRIX_VIEW = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MATRIX_PROJECTION = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MATRIX_MODEL = 9
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MATRIX_NORMAL = 10
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_VECTOR_VIEW = 11
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_COLOR_DIFFUSE = 12
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_COLOR_SPECULAR = 13
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_COLOR_AMBIENT = 14
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_ALBEDO = 15
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_METALNESS = 16
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_NORMAL = 17
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_ROUGHNESS = 18
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_OCCLUSION = 19
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_EMISSION = 20
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_HEIGHT = 21
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_CUBEMAP = 22
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_IRRADIANCE = 23
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_PREFILTER = 24
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_LOC_MAP_BRDF = 25

! ShaderUniformDataType
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_FLOAT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_VEC2 = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_VEC3 = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_VEC4 = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_INT = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_IVEC2 = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_IVEC3 = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_IVEC4 = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_UNIFORM_SAMPLER2D = 8

! ShaderAttributeDataType
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_ATTRIB_FLOAT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_ATTRIB_VEC2 = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_ATTRIB_VEC3 = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: SHADER_ATTRIB_VEC4 = 3

! PixelFormat
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_GRAYSCALE &
                                          = 1
integer(kind=c_int), parameter, public :: PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA   &
                                          = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R5G6B5 &
                                          = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R8G8B8 &
                                          = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 &
                                          = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 &
                                          = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 &
                                          = 7
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R32 &
                                          = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R32G32B32 &
                                          = 9
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: &
  PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 = 10
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R16 &
                                          = 11
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_UNCOMPRESSED_R16G16B16 &
                                          = 12
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: &
  PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 = 13
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_DXT1_RGB &
                                          = 14
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_DXT1_RGBA &
                                          = 15
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_DXT3_RGBA &
                                          = 16
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_DXT5_RGBA &
                                          = 17
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_ETC1_RGB &
                                          = 18
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_ETC2_RGB &
                                          = 19
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: &
  PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA = 20
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_PVRT_RGB &
                                          = 21
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: PIXELFORMAT_COMPRESSED_PVRT_RGBA &
                                          = 22
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: &
  PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA = 23

INTEGER(kind=C_INT), PARAMETER, PUBLIC :: &
  PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA = 24

! TextureFilter
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_POINT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_BILINEAR = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_TRILINEAR = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_ANISOTROPIC_4X = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_ANISOTROPIC_8X = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_FILTER_ANISOTROPIC_16X = 5

! TextureWrap
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_WRAP_REPEAT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_WRAP_CLAMP = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_WRAP_MIRROR_REPEAT = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: TEXTURE_WRAP_MIRROR_CLAMP = 3

! CubemapLayout
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_AUTO_DETECT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_LINE_VERTICAL = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_LINE_HORIZONTAL = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR &
                                          = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE &
                                          = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CUBEMAP_LAYOUT_PANORAMA = 5

! FontType
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FONT_DEFAULT = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FONT_BITMAP = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: FONT_SDF = 2

! BlendMode
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_ALPHA = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_ADDITIVE = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_MULTIPLIED = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_ADD_COLORS = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_SUBTRACT_COLORS = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_ALPHA_PREMULTIPLY = 5
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_CUSTOM = 6
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: BLEND_CUSTOM_SEPARATE = 7

! Gesture
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_NONE = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_TAP = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_DOUBLETAP = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_HOLD = 4
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_DRAG = 8
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_SWIPE_RIGHT = 16
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_SWIPE_LEFT = 32
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_SWIPE_UP = 64
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_SWIPE_DOWN = 128
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_PINCH_IN = 256
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: GESTURE_PINCH_OUT = 512

! CameraMode
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_CUSTOM = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_FREE = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_ORBITAL = 2
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_FIRST_PERSON = 3
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_THIRD_PERSON = 4

! CameraProjection
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_PERSPECTIVE = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: CAMERA_ORTHOGRAPHIC = 1

! NPatchLayout
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: NPATCH_NINE_PATCH = 0
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: NPATCH_THREE_PATCH_VERTICAL = 1
INTEGER(kind=C_INT), PARAMETER, PUBLIC :: NPATCH_THREE_PATCH_HORIZONTAL = 2

END MODULE RaylibEnums
