! ploDataElem is a post-processing software for T+H (TOUGH HYDRATE) program.
! It reads plot_data_elem file generated by T+H simulations and converts them
! vtu format. Which can then be visualized by usign PARAVIEW and other
! softwares.
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

!> author: Dr. Vikas Sharma
!
! [[Display_Method]] module consists small routines related
! to displaying the fortran variables on the screen

MODULE Display_Method
USE GlobalData
USE DISPMODULE
USE FACE
IMPLICIT NONE
PRIVATE
INTEGER(I4B), PARAMETER :: minRow = 4, minCol = 4
PUBLIC :: Display, BlankLines, DashLine
PUBLIC :: DotLine, EqualLine
PUBLIC :: TIMESTAMP
PUBLIC :: setDisplayProfile

CHARACTER(LEN=*), PARAMETER :: equal = "=============================="
CHARACTER(LEN=*), PARAMETER :: dot = ".............................."
CHARACTER(LEN=*), PARAMETER :: dash = "------------------------------"
CHARACTER(LEN=*), PARAMETER :: COLOR_FG = "CYAN"
CHARACTER(LEN=*), PARAMETER :: COLOR_BG = "BLACK"
CHARACTER(LEN=*), PARAMETER :: COLOR_STYLE = "BOLD_ON"

TYPE(DISP_SETTINGS), PUBLIC, PARAMETER :: &
  & DisplayProfileTerminal = DISP_SETTINGS(&
  & advance="YES", matsep=",", orient="COL", style="UNDERLINE", &
  & trim="FALSE", ZEROAS=".")
TYPE(DISP_SETTINGS), PUBLIC, PARAMETER :: &
  & DisplayProfilePrint = DISP_SETTINGS(&
  & advance="YES", matsep=",", orient="COL", style="UNDERLINE", &
  & trim="FALSE", ZEROAS="")
TYPE(DISP_SETTINGS), PARAMETER :: DisplayProfileOriginal = DISP_SETTINGS()
LOGICAL(LGT), SAVE :: defaultSettingSet = .FALSE.

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

INTERFACE Display
  MODULE PROCEDURE &
    & Display_Str, &
    & Display_Str2, &
    & Display_Real64, &
    & Display_Real32, &
    & Display_Int8, &
    & Display_Int16, &
    & Display_Int32, &
    & Display_Int64, &
    & Display_Logical, &
    & Display_Vector_Logical, &
    & Display_Vector_Real64, &
    & Display_Vector_Real32, &
    & Display_Vector_Int8, &
    & Display_Vector_Int16, &
    & Display_Vector_Int32, &
    & Display_Vector_Int64, &
    & Display_Mat2_Real64, &
    & Display_Mat2_Real32, &
    & Display_Mat2_Int64, &
    & Display_Mat2_Int32, &
    & Display_Mat2_Int16, &
    & Display_Mat2_Int8, &
    & Display_Mat3_Real64, &
    & Display_Mat3_Real32, &
    & Display_Mat3_Int64, &
    & Display_Mat3_Int32, &
    & Display_Mat3_Int16, &
    & Display_Mat3_Int8, &
    & Display_Mat4_Real64, &
    & Display_Mat4_Real32, &
    & Display_Mat4_Int64, &
    & Display_Mat4_Int32, &
    & Display_Mat4_Int16, &
    & Display_Mat4_Int8
END INTERFACE

CONTAINS

!----------------------------------------------------------------------------
!                                                         setDefaultSetting
!----------------------------------------------------------------------------

SUBROUTINE setDefaultSettings
  IF (defaultSettingSet) THEN
    RETURN
  ELSE
    CALL DISP_SET(DisplayProfileTerminal)
    defaultSettingSet = .TRUE.
  END IF
END SUBROUTINE setDefaultSettings

!----------------------------------------------------------------------------
!                                                          setDisplayProfile
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This routine sets the display profile

SUBROUTINE setDisplayProfile(DispProfile, advance, digmax, &
  & matsep, orient, sep, style, unit, zeroas)
  TYPE(DISP_SETTINGS), INTENT(IN) :: DispProfile
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: advance
  INTEGER(I4B), OPTIONAL, INTENT(IN) :: digmax
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: matsep
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: orient
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: sep
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: style
  INTEGER(I4B), OPTIONAL, INTENT(IN) :: unit
  CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: zeroas
  !> internal variables
  CALL DISP_SET(DispProfile)
  CALL DISP_SET(advance=advance, digmax=digmax, matsep=matsep, &
    & orient=orient, sep=sep, style=style, unit=unit, zeroas=zeroas)
END SUBROUTINE setDisplayProfile

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine Displays the string
!
!# Introduction
! This routine displays a string
!
!## usage
!```fortran
! CALL Display( msg="hello world", unitno=stdout )
!```

SUBROUTINE Display_Str(msg, unitno, advance)
  ! Dummt arguments
  CHARACTER(LEN=*), INTENT(IN) :: msg
  !! input message
  INTEGER(I4B), OPTIONAL, INTENT(IN) :: unitno
  !! unit no
  LOGICAL(LGT), OPTIONAL, INTENT(IN) :: advance
  ! Internal variables
  INTEGER(I4B) :: i
  CALL setDefaultSettings
  IF (PRESENT(unitno)) THEN
    i = unitno
  ELSE
    i = stdout
  END IF
#ifdef COLOR_DISP
  IF (PRESENT(advance)) THEN
    IF (advance) THEN
      CALL DISP(title="", &
        & x=TRIM(colorize(msg, color_fg=COLOR_FG, color_bg=COLOR_BG, &
        & style=COLOR_STYLE)), &
        & FMT='a', unit=i, style="left", advance="YES")
    ELSE
      CALL DISP(title="", &
        & x=TRIM(colorize(msg, color_fg=COLOR_FG, color_bg=COLOR_BG, &
        & style=COLOR_STYLE)), &
        & FMT='a', unit=i, style="left", advance="NO")
    END IF
  ELSE
    CALL DISP(title="", &
        & x=TRIM(colorize(msg, color_fg=COLOR_FG, color_bg=COLOR_BG, &
        & style=COLOR_STYLE)), &
        & FMT='a', unit=i, style="left")
  END IF
#else
  IF (PRESENT(advance)) THEN
    IF (advance) THEN
      CALL DISP(title="", x=msg, FMT='a', unit=i, style="left",  &
        & advance="YES")
    ELSE
      CALL DISP(title="", x=msg, FMT='a', unit=i, style="left",  &
        & advance="NO")
    END IF
  ELSE
    CALL DISP(title="", x=msg, FMT='a', unit=i, style="left")
  END IF
#endif
END SUBROUTINE Display_Str

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This routine prints a string; msg=val
!
!# Introduction
!
!  This routine prints a string; msg=val
!
!## Usage
!```fortran
!  CALL Display( val=" world!", msg="hello", stdout)
!```

SUBROUTINE Display_Str2(val, msg, unitno, advance)
  CHARACTER(LEN=*), INTENT(IN) :: val
  CHARACTER(LEN=*), INTENT(IN) :: msg
  INTEGER(I4B), OPTIONAL, INTENT(IN) :: unitno
  LOGICAL(LGT), OPTIONAL, INTENT(IN) :: advance
  ! internal variables
  CALL Display(msg=TRIM(msg)//TRIM(val), unitNo=unitNo, advance=advance)
END SUBROUTINE Display_Str2

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:         This subroutine display a scalar real number
!
!# Introduction
!
! This subroutine display a scalar real number
!
!## Usage
!
!```fortran
! call display( val=1.0_DFP, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Real64(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  REAL(REAL64), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Real64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:         This subroutine display a scalar real number
!
!# Introduction
!
! This subroutine display a scalar real number
!
!## Usage
!
!```fortran
! call display( val=1.0_DFP, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Real32(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  REAL(REAL32), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Real32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar integer number
!
!# Introduction
!
! This subroutine display a scalar integer number
!
!## Usage
!
!```fortran
!  call display( val=1.0_I4B, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Int64(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  INTEGER(INT64), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Int64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar integer number
!
!# Introduction
!
! This subroutine display a scalar integer number
!
!## Usage
!
!```fortran
!  call display( val=1.0_I4B, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Int32(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  INTEGER(INT32), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Int32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar integer number
!
!# Introduction
!
! This subroutine display a scalar integer number
!
!## Usage
!
!```fortran
!  call display( val=1.0_I4B, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Int16(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  INTEGER(INT16), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Int16

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar integer number
!
!# Introduction
!
! This subroutine display a scalar integer number
!
!## Usage
!
!```fortran
!  call display( val=1.0_I4B, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Int8(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  INTEGER(INT8), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Int8

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar logical variable
!
!# Introduction
!
! This subroutine display a scalar logical variable
!
!## Usage
!
!```fortran
!  call display( val=.TRUE., msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Logical(val, msg, unitNo, advance)
  ! Define intent of dummy variables
  LOGICAL(LGT), INTENT(IN) :: val
#include "./Display_Scalar.inc"
END SUBROUTINE Display_Logical

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a scalar logical variable
!
!# Introduction
!
! This subroutine display a scalar logical variable
!
!## Usage
!
!```fortran
!  call display( val=.TRUE., msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Vector_Logical(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  LOGICAL(LGT), INTENT(IN) :: val(:)
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Logical

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a vector of real numbers
!
!# Introduction
!  This subroutine display a vector of real numbers
!
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Real64(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  REAL(REAL64), INTENT(IN) :: val(:)
    !! vector of real numbers
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Real64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a vector of real numbers
!
!# Introduction
!  This subroutine display a vector of real numbers
!
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Real32(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  REAL(REAL32), INTENT(IN) :: val(:)
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Real32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:  This subroutine display a vector of integer numbers
!
!# Introduction
!
! This subroutine display a vector of integer numbers
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Int32(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT32), INTENT(IN) :: val(:)
  !! vector of real numbers
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Int32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:  This subroutine display a vector of integer numbers
!
!# Introduction
!
! This subroutine display a vector of integer numbers
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Int64(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT64), INTENT(IN) :: val(:)
  !! vector of real numbers
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Int64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:  This subroutine display a vector of integer numbers
!
!# Introduction
!
! This subroutine display a vector of integer numbers
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Int16(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT16), INTENT(IN) :: val(:)
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Int16

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary:  This subroutine display a vector of integer numbers
!
!# Introduction
!
! This subroutine display a vector of integer numbers
!
!### Usage
!
!```fortran
! real( dfp ) :: vec(10)
! call RANDOM_NUMBER(vec)
! call display( val=vec, msg="var=", unitno=stdout)
! call display( val=vec, msg="var=", unitno=stdout, orient="col")
!```

SUBROUTINE Display_Vector_Int8(val, msg, unitNo, orient, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT8), INTENT(IN) :: val(:)
#include "./Display_Vector.inc"
END SUBROUTINE Display_Vector_Int8

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a matrix of real numbers
!
!# Introduction
!
! ## Usage
! ```fortran
! real( dfp ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Real64(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  REAL(REAL64), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Real64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine display a matrix of real numbers
!
!# Introduction
!
! ## Usage
! ```fortran
! real( dfp ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Real32(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  REAL(REAL32), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Real32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine display a matrix of real numbers
!
! ## Usage
! ```fortran
! integer( i4b ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Int64(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT64), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Int64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine display a matrix of real numbers
!
! ## Usage
! ```fortran
! integer( i4b ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Int32(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT32), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Int32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine display a matrix of real numbers
!
! ## Usage
! ```fortran
! integer( i4b ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Int16(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT16), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Int16

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine display a matrix of real numbers
!
! ## Usage
! ```fortran
! integer( i4b ) :: mat(10, 10)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
! ```

SUBROUTINE Display_Mat2_Int8(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT8), DIMENSION(:, :), INTENT(IN) :: Val
#include "./Display_Mat2.inc"
END SUBROUTINE Display_Mat2_Int8

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
! ## Usage
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Real64(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  REAL(REAL64), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Real64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
! ## Usage
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Real32(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  REAL(REAL32), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Real32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
! ## Usage
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Int64(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT64), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Int64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
! ## Usage
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Int32(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT32), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Int32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Int16(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT16), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Int16

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the contents of a rank 3 array.
!
!# Introduction
!
! This subroutine displays the contents of a rank 3 array.
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(5, 5, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat3_Int8(Val, msg, unitNo, full, advance)
  !   Define intent of dummy variables
  INTEGER(INT8), INTENT(IN) :: Val(:, :, :)
#include "./Display_Mat3.inc"
END SUBROUTINE Display_Mat3_Int8

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Real64(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  REAL(REAL64), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Real64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Real32(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  REAL(REAL32), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Real32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Int64(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT64), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Int64

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Int32(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT32), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Int32

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Int16(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT16), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Int16

!----------------------------------------------------------------------------
!                                                                    Display
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This subroutine displays the content of rank4 matrix
!
!# Introduction
!
! This subroutine displays the content of rank4 matrix
!
!### Usage
!
!```fortran
! real( dfp ) :: mat(3, 3, 2, 2)
! call RANDOM_NUMBER(mat)
! call display( val=mat, msg="var=", unitno=stdout)
!```

SUBROUTINE Display_Mat4_Int8(Val, msg, unitNo, full, advance)
  ! Define intent of dummy variables
  INTEGER(INT8), INTENT(IN) :: Val(:, :, :, :)
#include "./Display_Mat4.inc"
END SUBROUTINE Display_Mat4_Int8

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Vikas Sharma, Ph. D.
! date: 21 Sept 2021
! summary: This function converts integer to character

FUNCTION Int2Str(I)
  ! Define intent of dummy arguments
  INTEGER(I4B), INTENT(IN) :: I
  CHARACTER(LEN=15) :: Int2Str
  ! Define internal variables
  CHARACTER(LEN=15) :: Str
  WRITE (Str, "(I15)") I
  Int2Str = TRIM(ADJUSTL(Str))
END FUNCTION Int2Str

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine prints blankline

SUBROUTINE BlankLines(unitNo, NOL)
  ! INTENT OF DUMMY VARIABLES
  INTEGER(I4B), INTENT(IN), OPTIONAL :: NOL, unitNo
  ! Define internal variables
  INTEGER(I4B) :: M = 1, I

  IF (PRESENT(NOL)) M = NOL

  IF (PRESENT(unitNo)) THEN
    DO I = 1, M
      WRITE (unitNo, "(A)") ""
    END DO
  ELSE
    DO I = 1, M
      WRITE (stdout, *) ""
    END DO
  END IF
END SUBROUTINE BlankLines

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine prints dash line

SUBROUTINE DashLine(unitNo)
  ! INTENT OF DUMMY VARIABLES
  INTEGER(I4B), INTENT(IN), OPTIONAL :: unitNo

  IF (PRESENT(unitNo)) THEN
    WRITE (unitNo, "(A)") dash
  ELSE
    WRITE (stdout, "(A)") dash
  END IF
END SUBROUTINE DashLine

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine prints dot line

SUBROUTINE DotLine(unitNo)
  ! INTENT OF DUMMY VARIABLES
  INTEGER(I4B), INTENT(IN), OPTIONAL :: unitNo

  IF (PRESENT(unitNo)) THEN
    WRITE (unitNo, "(A)") dot
  ELSE
    WRITE (stdout, "(A)") dot
  END IF

END SUBROUTINE DotLine

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine prints equal line

SUBROUTINE EqualLine(unitNo)
  ! INTENT OF DUMMY VARIABLES
  INTEGER(I4B), INTENT(IN), OPTIONAL :: unitNo

  IF (PRESENT(unitNo)) THEN
    WRITE (unitNo, "(A)") equal
  ELSE
    WRITE (stdout, "(A)") equal
  END IF

END SUBROUTINE EqualLine

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> author: Dr. Vikas Sharma
!
! This subroutine prints the time stamp

SUBROUTINE TIMESTAMP()
  ! Define Intent of dummy Variable
  CHARACTER(LEN=8) :: ampm
  INTEGER(I4B) :: d
  INTEGER(I4B) :: h
  INTEGER(I4B) :: m
  INTEGER(I4B) :: mm
  CHARACTER(LEN=9), PARAMETER, DIMENSION(12) :: month = (/ &
                         'January  ', 'February ', 'March    ', 'April    ', &
                         'May      ', 'June     ', 'July     ', 'August   ', &
                          'September', 'October  ', 'November ', 'December '/)
  INTEGER(I4B) :: n
  INTEGER(I4B) :: s
  INTEGER(I4B) :: values(8)
  INTEGER(I4B) :: y

  CALL DATE_AND_TIME(values=values)

  y = values(1)
  m = values(2)
  d = values(3)
  h = values(5)
  n = values(6)
  s = values(7)
  mm = values(8)

  IF (h < 12) THEN
    ampm = 'AM'
  ELSE IF (h == 12) THEN
    IF (n == 0 .AND. s == 0) THEN
      ampm = 'Noon'
    ELSE
      ampm = 'PM'
    END IF
  ELSE
    h = h - 12
    IF (h < 12) THEN
      ampm = 'PM'
    ELSE IF (h == 12) THEN
      IF (n == 0 .AND. s == 0) THEN
        ampm = 'Midnight'
      ELSE
        ampm = 'AM'
      END IF
    END IF
  END IF

  WRITE (*, '(8x, i2,1x,a,1x,i4,2x,i2,a1,i2.2,a1,i2.2,a1,i3.3,1x,a)') &
    d, TRIM(month(m)), y, h, ':', n, ':', s, '.', mm, TRIM(ampm)

END SUBROUTINE TIMESTAMP
END MODULE Display_Method
