! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

! #ifdef LONG__LONG
! #define LIS_INTEGER integer*8
! #else
! #define LIS_INTEGER integer
! #endif
!
! #ifdef LONG__DOUBLE
! #ifdef COMPLEX
! #define LIS_SCALAR complex*32
! #else
! #define LIS_SCALAR real*16
! #endif
! #define LIS_COMPLEX complex*32
! #define LIS_REAL real*16
! #else
! #ifdef COMPLEX
! #define LIS_SCALAR complex*16
! #else
! #define LIS_SCALAR real*8
! #endif
! #define LIS_COMPLEX complex*16
! #define LIS_REAL real*8
! #endif
!
! #define LIS_Comm LIS_INTEGER
!
! #ifdef USE_MPI
! #ifndef WIN32
! INCLUDE 'mpif.h'
! #else
! #include 'mpif.h'
! #endif
!
! #ifdef LONG__LONG
! #define LIS_MPI_INTEGER MPI_INTEGER
! #else
! #define LIS_MPI_INTEGER MPI_INTEGER
! #endif
!
! #define LIS_COMM_WORLD MPI_COMM_WORLD
! #else
! #define LIS_COMM_WORLD 1
! #endif

MODULE LISParam
USE GlobalData, ONLY: I4B, DFP, LGT, INT32, INT64
IMPLICIT NONE
PRIVATE

INTEGER(I4B), PUBLIC, PARAMETER :: LIS_TRUE = 1
INTEGER(I4B), PUBLIC, PARAMETER :: LIS_FALSE = 0
INTEGER(I4B), PUBLIC, PARAMETER :: LIS_INS_VALUE = 0
INTEGER(I4B), PUBLIC, PARAMETER :: LIS_ADD_VALUE = 1
INTEGER(I4B), PUBLIC, PARAMETER :: LIS_SUB_VALUE = 2
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_ASSEMBLING = 0
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_CSR = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_CSC = 2
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_MSR = 3
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_DIA = 4
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_CDS = 4
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_ELL = 5
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_JAD = 6
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_BSR = 7
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_BSC = 8
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_VBR = 9
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_COO = 10
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_DENSE = 11
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_DNS = 11
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_RCO = 255
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_TJAD = 12
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_BJAD = 13
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_BCR = 14
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_CJAD = 15
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_PCSR = 16
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_LCSR = 17
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_LJAD = 18
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_LBSR = 19
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_CDIA = 20
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_MSC = 21
INTEGER(i4b), public, PARAMETER :: LIS_MATRIX_DECIDING_SIZE = -(LIS_MATRIX_RCO + 1)
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_NULL = -(LIS_MATRIX_RCO + 2)
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_DEFAULT = LIS_MATRIX_CSR
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_POINT = LIS_MATRIX_CSR
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MATRIX_BLOCK = LIS_MATRIX_BSR
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_SCALE_NONE = 0
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_SCALE_JACOBI = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_SCALE_SYMM_DIAG = 2
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_AUTO = 0
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_PLAIN = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_MM = 2
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_LIS = 3
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_LIS_ASCII = 3
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_LIS_BINARY = 4
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_FREE = 5
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_ITBL = 6
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_HB = 7
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FMT_MMB = 8
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_BINARY_BIG = 0
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_BINARY_LITTLE = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_FAILS = -1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_SUCCESS = 0
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_ILL_OPTION = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_ERR_ILL_ARG = 1
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_BREAKDOWN = 2
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_OUT_OF_MEMORY = 3
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_ERR_OUT_OF_MEMORY = 3
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_MAXITER = 4
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_ERR_NOT_IMPLEMENTED = 5
INTEGER(i4b), PUBLIC, PARAMETER :: LIS_ERR_FILE_IO = 6

END MODULE LISParam
