#GMSH SDK
LIST( APPEND TARGET_COMPILE_DEF "-DBUILD_GMSH_INTERFACE" )
IF( UNIX )
  IF(APPLE)
    SET( GMSH_LIBRARIES "/usr/local/lib/libgmsh.dylib" )
  ELSE()
    SET( GMSH_LIBRARIES "$ENV{EASIFEM_EXTPKGS}/lib/libgmsh.so"  )
    # SET( GMSH_LIBRARIES "/home/vikassharma/miniconda3/envs/easifem/lib/python3.9/site-packages/gmsh-4.8.4-Linux64-sdk/lib/libgmsh.so"  )
  ENDIF()
ENDIF()
TARGET_LINK_LIBRARIES( ${PROJECT_NAME} PUBLIC ${GMSH_LIBRARIES} )
MESSAGE( STATUS "GMSH_LIBRARIES : ${GMSH_LIBRARIES}" )