# METIS LIBRARY
OPTION(USE_METIS OFF)
IF(USE_METIS)
  FIND_LIBRARY(METIS_LIB metis)
  MESSAGE("METIS_LIB = ${METIS_LIB}")
ENDIF()

TARGET_LINK_LIBRARIES(
  ${PROJECT_NAME}
  PUBLIC
  "$<$<BOOL:${USE_METIS}>:${METIS_LIB}>"
)