# FIND OPENMP
OPTION(USE_OpenMP OFF)
IF(USE_OpenMP)
  FIND_PACKAGE(OpenMP)
  IF(OpenMP_FOUND)
    MESSAGE(STATUS "OpenMP FOUND: ")
    LIST( APPEND TARGET_COMPILE_DEF "-DUSE_OpenMP" )
    LIST( APPEND TARGET_COMPILE_OPT ${OpenMP_Fortran_FLAGS}  )
  ELSE()
    MESSAGE(STATUS "OpenMP NOT FOUND: building without it")
  ENDIF()
ENDIF()
TARGET_LINK_LIBRARIES(
  ${PROJECT_NAME}
  PUBLIC
  ${LAPACK_LIBRARIES}
  ${BLAS_LIBRARIES}
  "$<$<BOOL:${OpenMP_FOUND}>:${OpenMP_Fortran_LIBRARIES}>"
)