IF(NOT CMAKE_PREFIX_PATH)
  LIST(
    APPEND
    CMAKE_PREFIX_PATH
    "$ENV{EASIFEM_EXTPKGS}"
    "$ENV{EASIFEM_BASE}"
    "$ENV{EASIFEM_CLASSES}"
    "$ENV{EASIFEM_MATERIALS}"
    "$ENV{EASIFEM_KERNELS}"
  )
ENDIF()