#COMPILE DEF

#Single precision or double precision
OPTION(USE_Real32 OFF)
OPTION(USE_Real64 OFF)
IF(USE_Real32)
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Real32" )
ELSEIF(USE_Real64)
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Real64" )
ELSE()
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Real64" )
ENDIF()
OPTION(USE_Int32 OFF)
OPTION(USE_Int64 OFF)
IF(USE_Int32)
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Int32" )
ELSEIF(USE_Real64)
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Int64" )
ELSE()
  LIST( APPEND TARGET_COMPILE_DEF "-DUSE_Int32" )
ENDIF()
LIST( APPEND TARGET_COMPILE_DEF "-D${CMAKE_HOST_SYSTEM_NAME}_SYSTEM" )

#DEFINE DEBUG
IF( $<CONFIG:DEBUG> )
  LIST( APPEND TARGET_COMPILE_DEF "-DDEBUG_VER" )
ENDIF()

#ADD TO PROJECT
TARGET_COMPILE_DEFINITIONS( ${PROJECT_NAME} PUBLIC ${TARGET_COMPILE_DEF} )
MESSAGE( STATUS "COMPILE DEFINITIONS USED ARE ${TARGET_COMPILE_DEF}")